[project]
name = "spotify-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.13.*"
dependencies = [
    "aiosqlite>=0.22.1",
    "humanize>=4.12.3",
    "nicegui[plotly]>=2.15.0",
    "polars>=1.31.0",
    "poldantic>=0.3.1",
    "pydantic>=2.11.7",
    "spotipy>=2.25.0",
    "sqlalchemy>=2.0.45",
]

[project.scripts]
spotify-analysis = "spotify_analysis.main:main"

[dependency-groups]
dev = [
    "pyinstrument>=5.1.2",
    "pytest>=9.0.2",
]

[build-system]
requires = ["uv_build>=0.9.23"]
build-backend = "uv_build"